import {db} from './db.js';
import {DEFAULT_PROFILE,AUTHORITY_NOTE} from './data.js';
import {
  SHRAVAN_CONFIG,
  ensureShravanRecipes,
  loadShravanSettings,
  saveShravanSettings,
  isShravanDate,
  recipesForPhase,
  recipeSelectable,
  phaseBadges,
  shravanRuleText,
  planningGuidance,
} from './shravan-phase.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={profile:structuredClone(DEFAULT_PROFILE),recipes:[],logs:[],category:'All',selected:null,shravan:{mode:'auto',wheyCompatible:false,showPremium:false}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const recipe=code=>state.recipes.find(r=>r.code===code);
const today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:state.profile.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`};
const addDays=(s,n)=>{const[y,m,d]=s.split('-').map(Number),x=new Date(y,m-1,d,12);x.setDate(x.getDate()+n);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const selectedDate=()=>$('#meal-date').value||today();
const shravanActive=()=>isShravanDate(selectedDate(),state.shravan);
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2200)}
function phaseList(category){return recipesForPhase(state.recipes,category,selectedDate(),state.shravan)}
function optionHtml(category,selected=''){const active=shravanActive();return `<option value="">None / custom</option>${phaseList(category).map(r=>{const disabled=!recipeSelectable(r,active,state.shravan);return `<option value="${esc(r.code)}" ${r.code===selected?'selected':''} ${disabled?'disabled':''}>${esc(r.code)} — ${esc(r.name)}${disabled?' — confirm whey first':''}</option>`}).join('')}`}
function fillPlanner(preserve=true){const current={Breakfast:$('#meal-breakfast').value,Lunch:$('#meal-lunch').value,Snack:$('#meal-snack').value,'Late top-up':$('#meal-topup').value};[['meal-breakfast','Breakfast'],['meal-lunch','Lunch'],['meal-snack','Snack'],['meal-topup','Late top-up']].forEach(([id,c])=>{const el=$('#'+id),selected=preserve?current[c]:'';el.innerHTML=optionHtml(c,selected);if(selected&&[...el.options].some(o=>o.value===selected))el.value=selected})}
function mainIngredients(r){const low=/^(water|salt|spices?|cinnamon|pepper|chilli|lemon|ginger|garlic|mustard|coriander|kasuri|turmeric|cumin|garam|bay leaf|ajwain|amchur|oregano|paprika|vinegar|hot sauce|cardamom)/i;return [...new Set((r.ingredients||[]).map(x=>x.split(':')[0].trim()).filter(x=>x&&!low.test(x)))].slice(0,4)}
function maxMinutes(r){const n=String(r.time||'').match(/\d+/g)?.map(Number)||[];return n.length?Math.max(...n):999}
function badges(r){const out=[],t=String(r.time||'').toLowerCase(),p=String(r.prepPacking||'').toLowerCase(),all=`${r.batchCooking||''} ${r.storage||''}`;out.push(...phaseBadges(r,shravanActive()));if(t.includes('no cooking')||t.includes('no-cook'))out.push('No cook');else if(maxMinutes(r)<=10)out.push('Quick');if(t.includes('soak')||p.includes('overnight')||p.includes('soak'))out.push('Prep ahead');if((r.perishable||r.coldPack)&&!out.includes('COLD PACK REQUIRED'))out.push('Keep cold');if(/batch|freeze|portions/i.test(all))out.push('Batch-friendly');return [...new Set(out)].slice(0,5)}
function selectedRecipes(){return ['meal-breakfast','meal-lunch','meal-snack','meal-topup'].map(id=>recipe($('#'+id).value)).filter(Boolean)}
function renderTotals(){const rs=selectedRecipes(),sum=k=>rs.reduce((s,r)=>s+(Number(r[k])||0),0),cal=sum('calories'),pro=sum('protein'),carb=sum('carbs'),fat=sum('fat');$('#meal-plan-totals').innerHTML=[['Calories',cal,`${Math.max(0,state.profile.calorieMax-cal)} remaining to maximum`],['Protein',`${pro.toFixed(1)} g`,`${Math.max(0,state.profile.proteinMin-pro).toFixed(1)} g remaining`],['Carbs',`${carb.toFixed(1)} g`,'Planning estimate'],['Fat',`${fat.toFixed(1)} g`,'Planning estimate']].map(([l,v,n])=>`<div class="mini-total"><span>${esc(l)}</span><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');const w=[];if(cal>state.profile.calorieMax)w.push('This combination may exceed 1,600 kcal.');if(!shravanActive()&&pro<state.profile.proteinMin)w.push('Estimated protein is below 110 g. A late top-up may be required.');if(!shravanActive()&&cal>state.profile.calorieMax&&pro<state.profile.proteinMin)w.push('Do not add a top-up automatically. Change the meal combination and confirm in Cronometer.');if(!shravanActive()&&rs.filter(r=>/Gusta/i.test(r.name)).length>=2)w.push('Two Gusta meals are selected today; consider a budget protein option tomorrow.');if(rs.some(r=>r.perishable||r.coldPack||r.requiresColdPack))w.push('At least one selected meal requires cold storage or an insulated bag with frozen cold packs.');w.push(...planningGuidance(rs,state.profile,shravanActive()));w.push(AUTHORITY_NOTE);$('#meal-plan-warnings').innerHTML=w.map(x=>`<div class="notice neutral">${esc(x)}</div>`).join('')}
function loadPlan(date){const l=state.logs.find(x=>x.date===date)||{};fillPlanner(false);$('#meal-breakfast').value=[...$('#meal-breakfast').options].some(o=>o.value===l.breakfastCode)?l.breakfastCode||'':'';$('#meal-lunch').value=[...$('#meal-lunch').options].some(o=>o.value===l.lunchCode)?l.lunchCode||'':'';$('#meal-snack').value=[...$('#meal-snack').options].some(o=>o.value===l.snackCode)?l.snackCode||'':'';$('#meal-topup').value=[...$('#meal-topup').options].some(o=>o.value===l.topUpCode)?l.topUpCode||'':'';renderTotals()}
async function savePlan(date=$('#meal-date').value){const active=shravanActive(),rs=selectedRecipes();if(active&&rs.some(r=>r.wheyCompatibilityRequired)&&!state.shravan.wheyCompatible)return toast('Confirm your current whey as Shravan-compatible before saving these meals.');if(active&&rs.filter(r=>r.grainMealOnly).length>1)return toast('Shravan permits one grain meal per calendar day.');const l=state.logs.find(x=>x.date===date)||{date};Object.assign(l,{breakfastCode:$('#meal-breakfast').value,lunchCode:$('#meal-lunch').value,snackCode:$('#meal-snack').value,topUpCode:$('#meal-topup').value,mealPhase:active?'shravan-2026':'normal'});await db.put('dailyLogs',l);const i=state.logs.findIndex(x=>x.date===date);i>=0?state.logs[i]=l:state.logs.push(l);toast(`Meal plan saved for ${date}.`)}
function setCategory(c){state.category=c;$$('.meal-category-button').forEach(b=>{const a=b.dataset.category===c;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});renderRecipes()}
function baseVisibleRecipes(){const cats=['Breakfast','Lunch','Snack','Late top-up'];const all=cats.flatMap(phaseList);return state.category==='All'?all:all.filter(r=>r.category===state.category)}
function filtered(){const q=$('#meal-search').value.trim().toLowerCase(),terms=$('#ingredient-filter').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),quick=$('#quick-only').checked,fav=$('#favourites-only').checked,high=$('#high-protein-only').checked;const list=baseVisibleRecipes().filter(r=>{const text=`${r.code} ${r.name} ${r.category} ${(r.ingredients||[]).join(' ')}`.toLowerCase();if(q&&!text.includes(q))return false;const ing=(r.ingredients||[]).join(' ').toLowerCase();if(terms.length&&!terms.every(t=>ing.includes(t)))return false;if(quick&&maxMinutes(r)>10&&!String(r.time).toLowerCase().includes('no cook'))return false;if(fav&&!r.favourite)return false;if(high&&Number(r.protein)<35)return false;return true});const sort=$('#meal-sort').value;return list.sort((a,b)=>sort==='quickest'?maxMinutes(a)-maxMinutes(b)||a.code.localeCompare(b.code):sort==='protein'?Number(b.protein)-Number(a.protein)||a.code.localeCompare(b.code):sort==='calories-low'?Number(a.calories)-Number(b.calories)||a.code.localeCompare(b.code):sort==='favourites'?Number(!!b.favourite)-Number(!!a.favourite)||a.code.localeCompare(b.code):a.code.localeCompare(b.code,undefined,{numeric:true}))}
function card(r){const ing=mainIngredients(r),b=badges(r),locked=!recipeSelectable(r,shravanActive(),state.shravan);return `<article class="meal-decision-card ${locked?'meal-locked':''}"><div class="meal-card-topline"><div class="meal-card-title"><span class="meal-code">${esc(r.code)}</span><span class="meal-category-label">${esc(r.category)}</span></div><button class="favourite-button" type="button" data-favourite="${esc(r.code)}" aria-label="Toggle favourite">${r.favourite?'★':'☆'}</button></div><h2>${esc(r.name)}</h2><div class="meal-card-time"><span>⏱</span><strong>Prep / cook:</strong> ${esc(r.time||'Not listed')}</div><div class="ingredient-preview"><span class="preview-label">Main ingredients</span><div class="ingredient-chips">${ing.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="recipe-macros decision-macros"><span><strong>${esc(r.calories)}</strong><small>kcal</small></span><span><strong>${esc(r.protein)} g</strong><small>protein</small></span><span><strong>${esc(r.carbs??'—')} g</strong><small>carbs</small></span><span><strong>${esc(r.fat??'—')} g</strong><small>fat</small></span></div>${b.length?`<div class="meal-badges">${b.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}${locked?'<div class="notice warning compact-notice">Confirm your current whey as Shravan-compatible before selecting this recipe.</div>':''}<div class="recipe-actions meal-card-actions"><button class="button secondary" type="button" data-view-recipe="${esc(r.code)}">View full recipe</button><button class="button primary" type="button" data-choose-recipe="${esc(r.code)}" ${locked?'disabled':''}>${locked?'Whey confirmation required':`Choose for ${esc(r.category.toLowerCase())}`}</button></div></article>`}
function renderRecipes(){const rs=filtered();$('#meal-result-count').textContent=`${rs.length} meal${rs.length===1?'':'s'} shown`;$('#meal-results').innerHTML=rs.length?rs.map(card).join(''):`<div class="empty-state"><h2>No meals match these filters</h2><p>Clear one or more filters or try another ingredient.</p><button id="clear-filters-empty" class="button secondary" type="button">Clear filters</button></div>`;$$('[data-view-recipe]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.viewRecipe));$$('[data-choose-recipe]').forEach(b=>b.onclick=()=>choose(b.dataset.chooseRecipe));$$('[data-favourite]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.favourite));$('#clear-filters-empty')?.addEventListener('click',clearFilters)}
function choose(code){const r=recipe(code);if(!recipeSelectable(r,shravanActive(),state.shravan))return toast('Confirm your current whey as Shravan-compatible first.');const id={Breakfast:'meal-breakfast',Lunch:'meal-lunch',Snack:'meal-snack','Late top-up':'meal-topup'}[r.category];if(!id)return;$('#'+id).value=code;renderTotals();$('#meal-planner').scrollIntoView({behavior:'smooth',block:'start'});toast(`${r.code} selected. Save the plan when ready.`)}
async function toggleFav(code){const r=recipe(code);r.favourite=!r.favourite;await db.put('recipes',r);renderRecipes();if(state.selected===code&&$('#recipe-dialog').open)openRecipe(code,true)}
function ruleCheck(r){if(!shravanActive())return '';return r.grainMealOnly?'Grain meal: normal salt, onion and garlic are permitted here. This L1-L10 meal uses the day’s single grain-meal allowance.':'Off-grain recipe: sendha namak only; no onion, garlic, paneer, soy/tofu, legumes, Gusta, normal vegetables, makhana or regular grains.'}
function openRecipe(code,preserve=false){const r=recipe(code);if(!r)return;state.selected=code;const b=badges(r),locked=!recipeSelectable(r,shravanActive(),state.shravan);$('#recipe-detail').innerHTML=`<div class="recipe-modal-heading"><div><span class="meal-code">${esc(r.code)}</span><p class="eyebrow">${esc(r.category)}</p><h2>${esc(r.name)}</h2></div><button class="favourite-button" type="button" data-modal-favourite="${esc(r.code)}">${r.favourite?'★':'☆'}</button></div><div class="recipe-modal-summary"><div><span>Prep / cook</span><strong>${esc(r.time)}</strong></div><div><span>Calories</span><strong>${esc(r.calories)} kcal</strong></div><div><span>Protein</span><strong>${esc(r.protein)} g</strong></div><div><span>Carbs / fat</span><strong>${esc(r.carbs??'—')} g / ${esc(r.fat??'—')} g</strong></div></div>${b.length?`<div class="meal-badges modal-badges">${b.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<section class="recipe-dialog-section"><h3>Exact ingredients</h3><ul>${(r.ingredients||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="recipe-dialog-section"><h3>Method</h3><ol>${(r.method||[]).map(x=>`<li>${esc(x.replace(/^\d+\.\s*/,''))}</li>`).join('')}</ol></section><div class="recipe-detail-notes"><p><strong>Make it taste excellent:</strong> ${esc(r.taste)}</p><p><strong>Prep / packing:</strong> ${esc(r.prepPacking)}</p>${r.batchCooking?`<p><strong>Batch cooking:</strong> ${esc(r.batchCooking)}</p>`:''}${r.storage?`<p><strong>Storage:</strong> ${esc(r.storage)}</p>`:''}${r.workPacking?`<p><strong>Work packing:</strong> ${esc(r.workPacking)}</p>`:''}${r.pairing?`<p><strong>Pairing:</strong> ${esc(r.pairing)}</p>`:''}<p><strong>Cronometer:</strong> ${esc(r.tracking)}</p>${shravanActive()?`<p><strong>Religious-rule check:</strong> ${esc(ruleCheck(r))}</p>`:''}</div>${locked?'<p class="notice warning">This recipe uses whey. Confirm the current product is Shravan-compatible before choosing it.</p>':''}<p class="authority-note">${esc(AUTHORITY_NOTE)}</p>`;$('#dialog-use-meal').textContent=locked?'Whey confirmation required':`Choose for ${r.category.toLowerCase()}`;$('#dialog-use-meal').disabled=locked;$('#dialog-use-meal').dataset.code=r.code;$('[data-modal-favourite]')?.addEventListener('click',()=>toggleFav(r.code));if(!preserve)$('#recipe-dialog').showModal()}
function clearFilters(){$('#meal-search').value='';$('#ingredient-filter').value='';$('#quick-only').checked=false;$('#favourites-only').checked=false;$('#high-protein-only').checked=false;$('#meal-sort').value='code';setCategory('All')}
function renderPhase(){const active=shravanActive(),auto=state.shravan.mode==='auto';$('#phase-mode').value=state.shravan.mode;$('#shravan-whey-compatible').checked=state.shravan.wheyCompatible;$('#shravan-premium').checked=state.shravan.showPremium;$('#shravan-status-chip').textContent=active?'Shravan active':'Normal plan';$('#shravan-status-chip').className=`status-chip ${active?'warning':'info'}`;$('#shravan-phase-description').textContent=active?`Shravan rules apply to ${selectedDate()}. One L1-L10 grain lunch; breakfast, snack and top-up are off-grain.`:`Normal meal plan for ${selectedDate()}.${auto?` Auto Shravan begins ${SHRAVAN_CONFIG.phase.activeFrom}.`:''}`;$('#shravan-rule-summary').innerHTML=active?`<strong>Today’s rule:</strong> ${esc(shravanRuleText())}${state.shravan.wheyCompatible?'':'<br><strong>Whey:</strong> not yet confirmed — Shravan whey recipes are visible but locked.'}`:`<strong>Normal mode.</strong> All normal recipes remain available. Shravan recipes stay in the database but are filtered out.`;$('#meal-structure-copy').textContent=active?'Choose 1 Shravan off-grain breakfast + 1 L1-L10 grain lunch + 1 Shravan off-grain snack + optional Shravan top-up.':'Choose one breakfast, one lunch, one snack and zero or one top-up.';const addons=$('#shravan-addons');addons.hidden=!active;if(active)addons.innerHTML=`<h3>Measured Shravan add-ons for calorie gaps</h3><p class="muted">Use these only when protein is already adequate but planned calories remain below 1,500.</p><div class="shravan-addon-grid">${SHRAVAN_CONFIG.shravanAddOns.map(a=>`<div><strong>${esc(a.code)} · ${esc(a.name)}</strong><span>${esc(a.portion)} · ${esc(a.planningCalories)} kcal</span><small>${esc(a.use)}</small></div>`).join('')}</div>`}
function refreshPhase(loadSaved=false){renderPhase();if(loadSaved)loadPlan(selectedDate());else{fillPlanner(true);renderTotals()}renderRecipes()}
async function savePhaseControls(){state.shravan={mode:$('#phase-mode').value,wheyCompatible:$('#shravan-whey-compatible').checked,showPremium:$('#shravan-premium').checked};state.shravan=await saveShravanSettings(db,state.shravan);refreshPhase(true);toast('Meal phase settings saved.')}
function bind(){$$('.meal-category-button').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));['meal-search','ingredient-filter'].forEach(id=>$('#'+id).oninput=renderRecipes);['quick-only','favourites-only','high-protein-only','meal-sort'].forEach(id=>$('#'+id).onchange=renderRecipes);$('#clear-meal-filters').onclick=clearFilters;['meal-breakfast','meal-lunch','meal-snack','meal-topup'].forEach(id=>$('#'+id).onchange=renderTotals);$('#meal-date').onchange=e=>{loadPlan(e.target.value);refreshPhase(true)};$('#save-meal-plan').onclick=()=>savePlan();$('#copy-plan-tomorrow').onclick=async()=>{const d=addDays($('#meal-date').value,1);await savePlan(d);$('#meal-date').value=d;refreshPhase(true)};$('#dialog-use-meal').onclick=()=>{choose($('#dialog-use-meal').dataset.code);if(!$('#dialog-use-meal').disabled)$('#recipe-dialog').close()};['phase-mode','shravan-whey-compatible','shravan-premium'].forEach(id=>$('#'+id).onchange=savePhaseControls)}
async function init(){const p=await db.get('settings','profile');if(p?.value)state.profile=p.value;else await db.put('settings',{key:'profile',value:state.profile});state.shravan=await loadShravanSettings(db);state.recipes=await ensureShravanRecipes(db);state.logs=await db.getAll('dailyLogs');document.documentElement.dataset.theme=state.profile.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.profile.theme;const d=today();$('#meal-date').min=state.profile.startDate;$('#meal-date').value=d;renderPhase();loadPlan(d);renderRecipes();bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
init().catch(e=>{console.error(e);$('#meal-results').innerHTML='<div class="notice warning">The meal library could not start. Reload the page or restore a valid tracker backup.</div>'});
