import {db} from './db.js';
import {DEFAULT_PROFILE,DEFAULT_RECIPES,AUTHORITY_NOTE} from './data.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={profile:structuredClone(DEFAULT_PROFILE),recipes:[],logs:[],category:'All',selected:null};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const recipe=code=>state.recipes.find(r=>r.code===code);
const today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:state.profile.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`};
const addDays=(s,n)=>{const[y,m,d]=s.split('-').map(Number),x=new Date(y,m-1,d,12);x.setDate(x.getDate()+n);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2200)}
function optionHtml(category,selected=''){return `<option value="">None / custom</option>${state.recipes.filter(r=>r.category===category&&r.code!=='None').map(r=>`<option value="${esc(r.code)}" ${r.code===selected?'selected':''}>${esc(r.code)} — ${esc(r.name)}</option>`).join('')}`}
function fillPlanner(){[['meal-breakfast','Breakfast'],['meal-lunch','Lunch'],['meal-snack','Snack'],['meal-topup','Late top-up']].forEach(([id,c])=>$('#'+id).innerHTML=optionHtml(c))}
function mainIngredients(r){const low=/^(water|salt|spices?|cinnamon|pepper|chilli|lemon|ginger|garlic|mustard|coriander|kasuri|turmeric|cumin|garam|bay leaf|ajwain|amchur|oregano|paprika|vinegar|hot sauce)/i;return [...new Set(r.ingredients.map(x=>x.split(':')[0].trim()).filter(x=>x&&!low.test(x)))].slice(0,4)}
function maxMinutes(r){const n=String(r.time||'').match(/\d+/g)?.map(Number)||[];return n.length?Math.max(...n):999}
function badges(r){const out=[],t=String(r.time||'').toLowerCase(),p=String(r.prepPacking||'').toLowerCase(),all=`${r.batchCooking||''} ${r.storage||''}`;if(t.includes('no cooking'))out.push('No cook');else if(maxMinutes(r)<=10)out.push('Quick');if(t.includes('soak')||p.includes('overnight')||p.includes('soak'))out.push('Prep ahead');if(r.perishable||r.coldPack)out.push('Keep cold');if(/batch|freeze|portions/i.test(all))out.push('Batch-friendly');return out.slice(0,3)}
function selectedRecipes(){return ['meal-breakfast','meal-lunch','meal-snack','meal-topup'].map(id=>recipe($('#'+id).value)).filter(Boolean)}
function renderTotals(){const rs=selectedRecipes(),sum=k=>rs.reduce((s,r)=>s+(Number(r[k])||0),0),cal=sum('calories'),pro=sum('protein'),carb=sum('carbs'),fat=sum('fat');$('#meal-plan-totals').innerHTML=[['Calories',cal,`${Math.max(0,state.profile.calorieMax-cal)} remaining to maximum`],['Protein',`${pro} g`,`${Math.max(0,state.profile.proteinMin-pro)} g remaining`],['Carbs',`${carb} g`,'Planning estimate'],['Fat',`${fat} g`,'Planning estimate']].map(([l,v,n])=>`<div class="mini-total"><span>${esc(l)}</span><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');const w=[];if(cal>state.profile.calorieMax)w.push('This combination may exceed 1,600 kcal.');if(pro<state.profile.proteinMin)w.push('Estimated protein is below 110 g. A late top-up may be required.');if(cal>state.profile.calorieMax&&pro<state.profile.proteinMin)w.push('Do not add a top-up automatically. Change the meal combination and confirm in Cronometer.');if(rs.filter(r=>/Gusta/i.test(r.name)).length>=2)w.push('Two Gusta meals are selected today; consider a budget protein option tomorrow.');if(rs.some(r=>r.perishable||r.coldPack))w.push('At least one meal requires cold storage or an insulated bag with frozen cold packs.');w.push(AUTHORITY_NOTE);$('#meal-plan-warnings').innerHTML=w.map(x=>`<div class="notice neutral">${esc(x)}</div>`).join('')}
function loadPlan(date){const l=state.logs.find(x=>x.date===date)||{};$('#meal-breakfast').value=l.breakfastCode||'';$('#meal-lunch').value=l.lunchCode||'';$('#meal-snack').value=l.snackCode||'';$('#meal-topup').value=l.topUpCode||'';renderTotals()}
async function savePlan(date=$('#meal-date').value){const l=state.logs.find(x=>x.date===date)||{date};Object.assign(l,{breakfastCode:$('#meal-breakfast').value,lunchCode:$('#meal-lunch').value,snackCode:$('#meal-snack').value,topUpCode:$('#meal-topup').value});await db.put('dailyLogs',l);const i=state.logs.findIndex(x=>x.date===date);i>=0?state.logs[i]=l:state.logs.push(l);toast(`Meal plan saved for ${date}.`)}
function setCategory(c){state.category=c;$$('.meal-category-button').forEach(b=>{const a=b.dataset.category===c;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});renderRecipes()}
function filtered(){const q=$('#meal-search').value.trim().toLowerCase(),terms=$('#ingredient-filter').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),quick=$('#quick-only').checked,fav=$('#favourites-only').checked,high=$('#high-protein-only').checked;const list=state.recipes.filter(r=>{if(r.code==='None'||(state.category!=='All'&&r.category!==state.category))return false;const text=`${r.code} ${r.name} ${r.category} ${r.ingredients.join(' ')}`.toLowerCase();if(q&&!text.includes(q))return false;const ing=r.ingredients.join(' ').toLowerCase();if(terms.length&&!terms.every(t=>ing.includes(t)))return false;if(quick&&maxMinutes(r)>10&&!String(r.time).toLowerCase().includes('no cooking'))return false;if(fav&&!r.favourite)return false;if(high&&Number(r.protein)<35)return false;return true});const sort=$('#meal-sort').value;return list.sort((a,b)=>sort==='quickest'?maxMinutes(a)-maxMinutes(b)||a.code.localeCompare(b.code):sort==='protein'?Number(b.protein)-Number(a.protein)||a.code.localeCompare(b.code):sort==='calories-low'?Number(a.calories)-Number(b.calories)||a.code.localeCompare(b.code):sort==='favourites'?Number(!!b.favourite)-Number(!!a.favourite)||a.code.localeCompare(b.code):a.code.localeCompare(b.code,undefined,{numeric:true}))}
function card(r){const ing=mainIngredients(r),b=badges(r);return `<article class="meal-decision-card"><div class="meal-card-topline"><div class="meal-card-title"><span class="meal-code">${esc(r.code)}</span><span class="meal-category-label">${esc(r.category)}</span></div><button class="favourite-button" type="button" data-favourite="${esc(r.code)}" aria-label="Toggle favourite">${r.favourite?'★':'☆'}</button></div><h2>${esc(r.name)}</h2><div class="meal-card-time"><span>⏱</span><strong>Prep / cook:</strong> ${esc(r.time||'Not listed')}</div><div class="ingredient-preview"><span class="preview-label">Main ingredients</span><div class="ingredient-chips">${ing.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="recipe-macros decision-macros"><span><strong>${esc(r.calories)}</strong><small>kcal</small></span><span><strong>${esc(r.protein)} g</strong><small>protein</small></span><span><strong>${esc(r.carbs??'—')} g</strong><small>carbs</small></span><span><strong>${esc(r.fat??'—')} g</strong><small>fat</small></span></div>${b.length?`<div class="meal-badges">${b.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<div class="recipe-actions meal-card-actions"><button class="button secondary" type="button" data-view-recipe="${esc(r.code)}">View full recipe</button><button class="button primary" type="button" data-choose-recipe="${esc(r.code)}">Choose for ${esc(r.category.toLowerCase())}</button></div></article>`}
function renderRecipes(){const rs=filtered();$('#meal-result-count').textContent=`${rs.length} meal${rs.length===1?'':'s'} shown`;$('#meal-results').innerHTML=rs.length?rs.map(card).join(''):`<div class="empty-state"><h2>No meals match these filters</h2><p>Clear one or more filters or try another ingredient.</p><button id="clear-filters-empty" class="button secondary" type="button">Clear filters</button></div>`;$$('[data-view-recipe]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.viewRecipe));$$('[data-choose-recipe]').forEach(b=>b.onclick=()=>choose(b.dataset.chooseRecipe));$$('[data-favourite]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.favourite));$('#clear-filters-empty')?.addEventListener('click',clearFilters)}
function choose(code){const r=recipe(code),id={Breakfast:'meal-breakfast',Lunch:'meal-lunch',Snack:'meal-snack','Late top-up':'meal-topup'}[r.category];if(!id)return;$('#'+id).value=code;renderTotals();$('#meal-planner').scrollIntoView({behavior:'smooth',block:'start'});toast(`${r.code} selected. Save the plan when ready.`)}
async function toggleFav(code){const r=recipe(code);r.favourite=!r.favourite;await db.put('recipes',r);renderRecipes();if(state.selected===code&&$('#recipe-dialog').open)openRecipe(code,true)}
function openRecipe(code,preserve=false){const r=recipe(code);if(!r)return;state.selected=code;const b=badges(r);$('#recipe-detail').innerHTML=`<div class="recipe-modal-heading"><div><span class="meal-code">${esc(r.code)}</span><p class="eyebrow">${esc(r.category)}</p><h2>${esc(r.name)}</h2></div><button class="favourite-button" type="button" data-modal-favourite="${esc(r.code)}">${r.favourite?'★':'☆'}</button></div><div class="recipe-modal-summary"><div><span>Prep / cook</span><strong>${esc(r.time)}</strong></div><div><span>Calories</span><strong>${esc(r.calories)} kcal</strong></div><div><span>Protein</span><strong>${esc(r.protein)} g</strong></div><div><span>Carbs / fat</span><strong>${esc(r.carbs??'—')} g / ${esc(r.fat??'—')} g</strong></div></div>${b.length?`<div class="meal-badges modal-badges">${b.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<section class="recipe-dialog-section"><h3>Exact ingredients</h3><ul>${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="recipe-dialog-section"><h3>Method</h3><ol>${r.method.map(x=>`<li>${esc(x.replace(/^\d+\.\s*/,''))}</li>`).join('')}</ol></section><div class="recipe-detail-notes"><p><strong>Make it taste excellent:</strong> ${esc(r.taste)}</p><p><strong>Prep / packing:</strong> ${esc(r.prepPacking)}</p><p><strong>Batch cooking:</strong> ${esc(r.batchCooking)}</p><p><strong>Storage:</strong> ${esc(r.storage)}</p><p><strong>Work packing:</strong> ${esc(r.workPacking)}</p><p><strong>Pairing:</strong> ${esc(r.pairing)}</p><p><strong>Cronometer:</strong> ${esc(r.tracking)}</p></div><p class="authority-note">${esc(AUTHORITY_NOTE)}</p>`;$('#dialog-use-meal').textContent=`Choose for ${r.category.toLowerCase()}`;$('#dialog-use-meal').dataset.code=r.code;$('[data-modal-favourite]')?.addEventListener('click',()=>toggleFav(r.code));if(!preserve)$('#recipe-dialog').showModal()}
function clearFilters(){$('#meal-search').value='';$('#ingredient-filter').value='';$('#quick-only').checked=false;$('#favourites-only').checked=false;$('#high-protein-only').checked=false;$('#meal-sort').value='code';setCategory('All')}
function bind(){$$('.meal-category-button').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));['meal-search','ingredient-filter'].forEach(id=>$('#'+id).oninput=renderRecipes);['quick-only','favourites-only','high-protein-only','meal-sort'].forEach(id=>$('#'+id).onchange=renderRecipes);$('#clear-meal-filters').onclick=clearFilters;['meal-breakfast','meal-lunch','meal-snack','meal-topup'].forEach(id=>$('#'+id).onchange=renderTotals);$('#meal-date').onchange=e=>loadPlan(e.target.value);$('#save-meal-plan').onclick=()=>savePlan();$('#copy-plan-tomorrow').onclick=async()=>{const d=addDays($('#meal-date').value,1);await savePlan(d);$('#meal-date').value=d;loadPlan(d)};$('#dialog-use-meal').onclick=()=>{choose($('#dialog-use-meal').dataset.code);$('#recipe-dialog').close()};$('#theme').onclick=async()=>{const dark=document.documentElement.dataset.theme==='dark';state.profile.theme=dark?'light':'dark';document.documentElement.dataset.theme=state.profile.theme;await db.put('settings',{key:'profile',value:state.profile})}}
async function init(){const p=await db.get('settings','profile');if(p?.value)state.profile=p.value;else await db.put('settings',{key:'profile',value:state.profile});state.recipes=await db.getAll('recipes');if(!state.recipes.length){state.recipes=structuredClone(DEFAULT_RECIPES);await db.bulkPut('recipes',state.recipes)}state.logs=await db.getAll('dailyLogs');document.documentElement.dataset.theme=state.profile.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.profile.theme;fillPlanner();const d=today();$('#meal-date').min=state.profile.startDate;$('#meal-date').value=d;loadPlan(d);renderRecipes();bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
init().catch(e=>{console.error(e);$('#meal-results').innerHTML='<div class="notice warning">The meal library could not start. Reload the page or restore a valid tracker backup.</div>'});
